config/routes.rb
Rails.application.routes.draw do

  resources :calculated_positions, only: :index

  resources :ranking_configs, only: [:edit, :update]

  resources :reports, only: [:edit, :update]

  resources :reports do
    member do
      patch 'confirm'
    end
  end
  devise_for :users

  resources :users, only: [:index, :show]

  resources :users do
    resources :profiles, only: :index
    resources :reports, only: :index
  end

  resources :games do
    resources :rankings, only: [:index, :new, :create]
    resources :possible_results

  end

  resources :scenarios do
    resources :reports
  end

  resources :rankings do
    resources :scenarios, only: [:index, :new, :create]
    resources :calculated_positions, only: [:index]
    resources :ranking_configs, only: [:show, :new, :create, :edit, :update]

  end

  resources :reports, only: [:index, :edit, :update]

  get 'pages/home'
  get 'pages/how_it_works'

  get 'pages/admin'

  devise_scope :user do
    get 'install', to: 'new_super_admin#new'
    post 'create_super_admin', to: 'create_super_admin#create'
  end

  get 'pages/access_denied'

  root 'pages#home'

  resources :profiles do
    member do
      get :switch_to
    end
  end

end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  before_create :build_default_config

  belongs_to :game
  has_many :scenarios
  has_many :reports, through: :scenarios
  has_many :calculated_positions
  has_one :ranking_config
  has_many :ranked_positions


  validates :name, presence: true
  validates :description, presence: true
  validates :game_id, presence: true

  resourcify

  private
  def build_default_config
    default_config = RankingConfig.default_config.dup
    # default_config
    self.ranking_config = default_config
    self.ranking_config.is_default = false
    # RankingConfig.new(is_default: false, hours_to_confirm: 49, default_score: 233)
    # self.ranking_config.save
    true
  end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  before_action :set_ranking, only: [:show]

  def index
    if params[:game_id]
      @game = Game.find(params[:game_id].to_i)
      @header = "Rankings of #{@game.short_name}"
      @rankings = @game.rankings
      add_breadcrumb @game.short_name, @game
      add_breadcrumb "Rankings", :rankings_path


    else
      @header = "Rankings"
      @rankings = Ranking.includes(:game, :scenarios)
      add_breadcrumb "Rankings", :rankings_path

    end
  end

  def show
    @config = @ranking.ranking_config
    @ranked_positions = @ranking.ranked_positions
    add_breadcrumb @ranking.game.short_name, @ranking.game
    add_breadcrumb "rankings", game_rankings_path(@ranking.game)
    add_breadcrumb @ranking.name, @ranking

  end

  def new
    @game = Game.find(params[:game_id].to_i)
    @ranking = Ranking.new
    @ranking.game = @game
  end

  def create
    @game = Game.find(params[:game_id])
    @ranking = Ranking.new(ranking_params)
    @ranking.game = @game
    if @ranking.save
      redirect_to @ranking, notice: 'Ranking was successfully created.'
    else
      render :new
    end
  end

  private

  def set_ranking
    @ranking = Ranking.find(params[:id])
  end

  def ranking_params
    params.require(:ranking).permit(:name, :description)
  end

end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/views/rankings/_form.html.erb
<%= form_for([@game, @ranking]) do |f| %>

  <% if @ranking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ranking.errors.count, "error") %> prohibited this ranking from being saved:</h2>

      <ul>
        <% @ranking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="form-group">
    <%# f.label :game, "The game" %><br />
    <%# f.collection_select(:game_id, Game.all, :id, :full_name, include_blank: true) %>
  </div> -->
  <!-- <%#f.hidden_field :task_id, :value => task.id%> -->
  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>

<% end %>

app/views/rankings/_ranked_positions_index.html.erb
<h1>Leaderboard</h1>
<% if ranked_positions.any? %>

  <table class="table">
    <thead>
      <tr>
        <th>Profile name</th>
        <th>User ID</th>
        <th>Current score</th>
        <th>Last score change</th>
        <th>Number of matche</th>
        <th>Number of wins</th>
        <th>Average score per win</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% ranked_positions.each do |position| %>
        <tr>
          <td><%= position.profile.name %></td>
          <td><%= position.profile.user.id %></td>
          <td><%= position.current_score %></td>
          <td><%= position.last_score_gained %></td>
          <td><%= position.number_of_won_matches %></td>
          <td><%= position.average_win_score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>
 <p> Nothing to display. </p>
<% end %>

app/views/rankings/index.html.erb
<h1><%= @header %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Ranking id</th>
      <th>Name</th>
      <th>Game</th>
      <th>Description</th>
      <th>Scenarios</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rankings.each do |ranking| %>
      <tr>
        <td><%= ranking.id %></td>
        <td><%= link_to ranking.name, ranking %></td>
        <td><%= link_to ranking.game.short_name, ranking.game %></td>
        <td><%= truncate(ranking.description, length: 500, separator: ' ') %></td>
        <td>
          <% number_of_scenarios = ranking.scenarios.count %>
          <% if number_of_scenarios > 0 %>
            <%= link_to number_of_scenarios, ranking_scenarios_path(ranking) %>
          <% else %>
            0
          <% end %>
        </td>
        <td><%= link_to 'Create a new scenario', new_ranking_scenario_path(ranking) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/rankings/new.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h2><%= @game.full_name %> / New Ranking</h1>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>

  <div class="panel-footer">
    <%= link_to 'Back', rankings_path %>
  </div>

</div>

app/views/rankings/show.html.erb
<h1><%= @ranking.name %></h1>
<p><%= @ranking.description %></p>

<h2>The ranking configuration</h2>


<table class="table">
  <thead>
    <tr>
      <th>Ranking config ID</th>
      <th>Ranking ID</th>
      <th>Is default?</th>
      <th>Starting ranking</th>
      <th>Max dist. between players</th>
      <th>Min points to gain</th>
      <th>Disproportion factor</th>
      <th>Unexpected result bonus</th>
      <th>Hours to confirm</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @config.id %></td>
      <td><%= @ranking.id %></td>
      <td><%= @config.is_default? %></td>
      <td><%= @config.default_score %></td>
      <td><%= @config.max_distance_between_players %></td>
      <td><%= @config.min_points_to_gain %></td>
      <td><%= @config.disproportion_factor %></td>
      <td><%= @config.unexpected_result_bonus %></td>
      <td><%= @config.hours_to_confirm %></td>
    </tr>
  </tbody>
</table>

<% if user_signed_in? %>
  <% if @ranking.ranking_config %>
    <%= link_to 'Edit the ranking ranking config', edit_ranking_ranking_config_path(@ranking, @ranking.ranking_config), class: "btn btn-danger" %>
  <% else %>
    <%= link_to 'Create a new ranking ranking config', new_ranking_ranking_config_path(@ranking), class: "btn btn-success" %>
  <% end %>
<% end %>

<%= render partial: "ranked_positions_index", locals: {ranked_positions: @ranked_positions} %>