config/routes.rb
Rails.application.routes.draw do

  resources :calculated_positions, only: :index

  resources :ranking_configs, only: [:edit, :update]

  resources :reports, only: [:edit, :update]

  resources :reports do
    member do
      patch 'confirm'
    end
  end
  devise_for :users

  resources :users, only: [:index, :show]

  resources :users do
    resources :profiles, only: :index
    resources :reports, only: :index
  end

  resources :games do
    resources :rankings, only: [:index, :new, :create]
    resources :possible_results

  end

  resources :scenarios do
    resources :reports
  end

  resources :rankings do
    resources :scenarios, only: [:index, :new, :create]
    resources :calculated_positions, only: [:index]
    resources :ranking_configs, only: [:show, :new, :create, :edit, :update]

  end

  resources :reports, only: [:index, :edit, :update]

  get 'pages/home'
  get 'pages/how_it_works'

  get 'pages/admin'

  devise_scope :user do
    get 'install', to: 'new_super_admin#new'
    post 'create_super_admin', to: 'create_super_admin#create'
  end

  get 'pages/access_denied'

  root 'pages#home'

  resources :profiles do
    member do
      get :switch_to
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :rankings
  has_many :scenarios, through: :rankings
  has_many :ranked_positions, through: :rankings
  has_many :reports, through: :scenarios
  has_many :factions
  has_many :possible_results

  accepts_nested_attributes_for :possible_results, reject_if: :all_blank, allow_destroy: true

  resourcify

  def count_reports
    number_of_reports = 0
    self.rankings.each do |ranking|
       ranking.scenarios.each do |scenario|
         scenario.reports.each do |report|
           number_of_reports += 1
         end
       end
    end
    number_of_reports
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show]

  def index
    @games = Game.all
    add_breadcrumb "Games", :games_path

  end

  def show
    @results = @game.possible_results
    add_breadcrumb "Games", :games_path
    add_breadcrumb @game.short_name, @game

  end

  def new
    @game = Game.new
    @game.description = "Type here something about the game."
    @game.possible_results << PossibleResult.new(description: "Victory", score_factor: 100)
    @game.possible_results << PossibleResult.new(description: "Defeat", score_factor: 0)
    @game.possible_results << PossibleResult.new(description: "Draw", score_factor: 50)
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render :new
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def game_params
    params.require(:game).permit(:full_name, :short_name, :description, :simultaneous_turns, possible_results_attributes: [:id, :description, :score_factor, :_destroy])
  end

end

app/helpers/games_helper.rb
module GamesHelper


  def link_to_game_laders(game)
    "SHIT"
  end
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% @game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.check_box :simultaneous_turns, class: 'checkbox' %>
    <%= f.label :simultaneous_turns %>
  </div>

  <h3>Possible results</h3>
  <div class="">
    <%= f.fields_for :possible_results do |result| %>
      <%= render 'possible_result_fields', f: result %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add another result', f, :possible_results, class: "btn btn-default" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>

<% end %>

app/views/games/_possible_result_fields.html.erb
<div class="nested-fields ">
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :score_factor %>
    <%= f.number_field :score_factor %>
  </div>
  <%= link_to_remove_association "Remove", f %>
</div>

app/views/games/index.html.erb
<h1>Games</h1>


<table class="table">
  <thead>
    <tr>
      <th>Game id</th>
      <th>Name</th>
      <th>Description</th>
      <th>Rankings</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.id %></td>
        <td><%= link_to game.full_name, game %></td>
        <td><%= truncate(game.description, length: 500, separator: ' ') %></td>
        <td>
          <% number_of_rankings = game.rankings.count %>
          <% if number_of_rankings > 0 %>
            <%= link_to number_of_rankings, game_rankings_path(game) %>
          <% else %>
            0
          <% end %>
        </td>
      <td><%= link_to 'Create a new ranking', new_game_ranking_path(game) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'Create a new game', new_game_path, class: "btn btn-danger" %>
<% end %>

app/views/games/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New Game</h1>
  </div>


  <div class="panel-body">
    <%= render 'form' %>
  </div>



  <div class="panel-footer">
    <%= link_to 'Back', games_path %>
  </div>
</div>

app/views/games/show.html.erb
<h1><%= @game.full_name %></h1>
<p><%= @game.description %></p>

<h4>Possible results of the game:</h4>
<% if !@results.empty? %>
  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Description</th>
        <th>Score factor</th>
        <th>Edit</th>
      </tr>
    </thead>
    <tbody>
      <% @results.each do |result| %>
        <tr>
          <td><%= result.id %></td>
          <td><%= result.description %></td>
          <td><%= result.score_factor %></td>
          <td><%= link_to "Edit", edit_game_possible_result_path(game_id: @game, id: result) %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No possible results. Please make some or it will be impossible to report any results.</p>
<% end %>
<% if user_signed_in? %>
  <%= link_to 'Create a new possible result', new_game_possible_result_path(game_id: @game), class: "btn btn-danger" %>
<% end %>