config/routes.rb
Rails.application.routes.draw do

  resources :calculated_positions, only: :index

  resources :ranking_configs, only: [:edit, :update]

  resources :reports, only: [:edit, :update]

  resources :reports do
    member do
      patch 'confirm'
    end
  end
  devise_for :users

  resources :users, only: [:index, :show]

  resources :users do
    resources :profiles, only: :index
    resources :reports, only: :index
  end

  resources :games do
    resources :rankings, only: [:index, :new, :create]
    resources :possible_results

  end

  resources :scenarios do
    resources :reports
  end

  resources :rankings do
    resources :scenarios, only: [:index, :new, :create]
    resources :calculated_positions, only: [:index]
    resources :ranking_configs, only: [:show, :new, :create, :edit, :update]

  end

  resources :reports, only: [:index, :edit, :update]

  get 'pages/home'
  get 'pages/how_it_works'

  get 'pages/admin'

  devise_scope :user do
    get 'install', to: 'new_super_admin#new'
    post 'create_super_admin', to: 'create_super_admin#create'
  end

  get 'pages/access_denied'

  root 'pages#home'

  resources :profiles do
    member do
      get :switch_to
    end
  end

end

app/models/scenario.rb
class Scenario < ActiveRecord::Base
  belongs_to :ranking
  has_many :reports
  has_many :faction_to_scenario_assignments
  has_many :factions, through: :faction_to_scenario_assignments
  belongs_to :game
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  before_action :set_scenario, only: [:show]

  def index
    if params[:ranking_id]
      @ranking = Ranking.find(params[:ranking_id].to_i)
      @header = "Scenarios of #{@ranking.name}"
      @scenarios = @ranking.scenarios
      add_breadcrumb "Games", :games_path
      add_breadcrumb @ranking.game.short_name, @ranking.game
      add_breadcrumb "rankings", game_rankings_path(@ranking.game)
      add_breadcrumb @ranking.name, @ranking
      add_breadcrumb "scenarios", :ranking_scenarios_path

    else
      @header = "Scenarios"
      @scenarios = Scenario.all
      add_breadcrumb "Scenarios", scenarios_path

    end
  end

  def show
    add_breadcrumb "Games", :games_path
    add_breadcrumb @scenario.ranking.game.short_name, @scenario.ranking.game
    add_breadcrumb "rankings", game_rankings_path(@scenario.ranking.game)
    add_breadcrumb @scenario.ranking.name, @scenario.ranking
    add_breadcrumb "scenarios", ranking_scenarios_path(@scenario.ranking)
    add_breadcrumb @scenario.short_name, @scenario

  end

  def new
    @scenario = Scenario.new
    @ranking = Ranking.find(params[:ranking_id].to_i)
    @game = @ranking.game
    @scenario.ranking = @ranking
  end

  def create
    @ranking = Ranking.find(params[:ranking_id])
    @scenario = Scenario.new(scenario_params)
    @scenario.ranking = @ranking
    if @scenario.save
      redirect_to @scenario, notice: 'Scenario was successfully created.'
    else
      render :new
    end
  end


  private

  def set_scenario
    @scenario = Scenario.find(params[:id])
  end

  def scenario_params
    params.require(:scenario).permit(:full_name,:short_name, :description, :ranking_id, :map_size, :mirror_matchups_allowed, :map_random_generated)
  end

end

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/_form.html.erb
<%= form_for([@ranking, @scenario]) do |f| %>

  <% if @scenario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scenario.errors.count, "error") %> prohibited this scenario from being saved:</h2>

      <ul>
        <% @scenario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="form-group">
    <%= f.label :ranking, "The ranking" %><br />
    <%= f.collection_select(:ranking_id, @ranking.game.rankings, :id, :name, include_blank: true) %>
  </div> -->

  <div class="form-group">
    <%= f.label :full_name %><br />
    <%= f.text_field :full_name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :short_name %><br />
    <%= f.text_field :short_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br />
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.check_box :mirror_matchups_allowed, class: 'checkbox' %>
    <%= f.label :mirror_matchups_allowed %>
  </div>

  <div class="form-group">
    <%= f.check_box :map_random_generated, class: 'checkbox' %>
    <%= f.label :map_random_generated %>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>

<% end %>

app/views/scenarios/index.html.erb
<h1><%= @header %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Scenario id</th>
      <th>Name</th>
      <th>Description</th>
      <th> </th>

    </tr>
  </thead>

  <tbody>
    <% @scenarios.each do |scenario| %>
      <tr>
        <td><%= scenario.id %></td>
        <td><%= link_to scenario.short_name, scenario %></td>
        <td><%= truncate(scenario.description, length: 500, separator: ' ') %></td>
        <td><%= link_to 'Report new game', new_scenario_report_path(scenario.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/scenarios/new.html.erb
<div class="panel panel-default">

  <div class="panel-heading">
    <h2><%= @ranking.game.full_name %> / <%= @ranking.name %> / New Scenario</h1>
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>

  <div class="panel-footer">
    <%= link_to 'Back', scenarios_path %>
  </div>

</div>

app/views/scenarios/show.html.erb
<h1><%= @scenario.full_name %></h1>
<p><%= @scenario.description %></p>