config/routes.rb
Rails.application.routes.draw do

  resources :calculated_positions, only: :index

  resources :ranking_configs, only: [:edit, :update]

  resources :reports, only: [:edit, :update]

  resources :reports do
    member do
      patch 'confirm'
    end
  end
  devise_for :users

  resources :users, only: [:index, :show]

  resources :users do
    resources :profiles, only: :index
    resources :reports, only: :index
  end

  resources :games do
    resources :rankings, only: [:index, :new, :create]
    resources :possible_results

  end

  resources :scenarios do
    resources :reports
  end

  resources :rankings do
    resources :scenarios, only: [:index, :new, :create]
    resources :calculated_positions, only: [:index]
    resources :ranking_configs, only: [:show, :new, :create, :edit, :update]

  end

  resources :reports, only: [:index, :edit, :update]

  get 'pages/home'
  get 'pages/how_it_works'

  get 'pages/admin'

  devise_scope :user do
    get 'install', to: 'new_super_admin#new'
    post 'create_super_admin', to: 'create_super_admin#create'
  end

  get 'pages/access_denied'

  root 'pages#home'

  resources :profiles do
    member do
      get :switch_to
    end
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :scenario
  belongs_to :reporter, foreign_key: 'reporter_id', class_name: 'Profile'
  belongs_to :confirmer, foreign_key: 'confirmer_id', class_name: 'Profile'
  belongs_to :reporters_faction, foreign_key: 'reporters_faction_id', class_name: 'Faction'
  belongs_to :confirmers_faction, foreign_key: 'confirmers_faction_id', class_name: 'Faction'
  has_many :calculated_positions
  has_many :report_comments
  belongs_to :result, foreign_key: 'result_id', class_name: 'PossibleResult'

  attr_accessor :confirmers_name, :was_just_confirmation

  enum status: { unconfirmed: 0, confirmed: 1, to_calculate: 2, calculated:3 }

  validates :scenario_id, presence: true
  validates :reporter_id, presence: {message: "Your name can't be blank"}
  validates :confirmer_id, presence: {message: "Name of your opponent can't be blank"}
  validates :reporters_faction_id, presence: {message: "Your faction can't be blank"}
  validates :confirmers_faction_id, presence: {message: "Faction of your opponent can't be blank"}
  validates :result_id, presence: true

  validate :profiles_are_from_different_users

  def profiles_are_from_different_users
    if reporter_id and confirmer_id
      if self.reporter.user_id == self.confirmer.user_id
        # self.errors.add(:confirmer, "profile belongs to you. Are you trying to cheat?")
        self.errors[:base] << "Your opponent's profile belongs to YOU!"
      end
    end

  end

  def handle_possible_confirmation
    @was_just_confirmation = false
    report_to_confirm = original_report

    if report_to_confirm
      report_to_confirm.confirmed!
      report_to_confirm.was_just_confirmation = true
      report_to_confirm.save
      return report_to_confirm
    end
    self
  end

  def was_just_confirmation?
    @was_just_confirmation
  end

  def previous(player)
    Report.where(scenario_id: scenario.id).where(["reporter_id = ? OR confirmer_id = ?", player.id, player.id]).where(["id < ?", id]).last
  end

  def self.by_profile(profile)
    Report.where(["reporter_id = ? OR confirmer_id = ?", profile.id, profile.id])
  end

  def self.to_confirm_by_user(user)
    Report.where(confirmer: user.profiles).unconfirmed.count
  end

  def confirm
    self.confirmed! if self.unconfirmed?
  end

  private

  def original_report
    number_of_hours = scenario.ranking.ranking_config.hours_to_confirm
    opposite_results = PossibleResult.where(game_id: scenario.ranking.game).where(score_factor: add_inv(result.score_factor))

    Report.where(status: "unconfirmed").where(scenario_id: scenario_id).where("created_at > ?", number_of_hours.hours.ago).where({reporter_id: confirmer_id, confirmer_id: reporter_id}).where({reporters_faction_id: confirmers_faction_id, confirmers_faction_id: reporters_faction_id}).where(result: opposite_results).first
  end

  def add_inv(number)
    hundred_percent = 100
    hundred_percent - number
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
    if params[:ranking_id]
      @ranking = Ranking.find(params[:ranking_id].to_i)
      @header = "Reports of #{@ranking.name}"
      @reports = @ranking.reports

    elsif params[:profile]
      begin
        @profile = Profile.find(params[:profile])
        @header = "Reports for #{@profile.name}"
        @reports = Report.by_profile(@profile)
      rescue ActiveRecord::RecordNotFound
        @header = "Reports for profile ID #{params[:profile]}"
        render :no_profile_error
      end
    elsif params[:user_id]
      user = User.find(params[:user_id])
      @reports = Report.where(["reporter_id = ? OR confirmer_id = ?", user.profiles.pluck(:id), user.profiles.pluck(:id)])

    else
      @header = "Reports"
      @reports = Report.all
      add_breadcrumb "Reports", :reports_path
    end
  end

  def confirm
    report = Report.find(params[:id])
    report.confirm
    ReportsToCalculateFinder.new(report).tag_to_calculate
    ReportsCalculating.new(report.scenario.ranking).calculate
    LeaderboardUpdater.update
    redirect_to user_reports_path(params[:user_id]), notice: 'Report was successfully confirmed.'
  end

  def new
    @report = Report.new
    if params[:scenario_id]
      @scenario = Scenario.find(params[:scenario_id])
      @report.scenario_id = params[:scenario_id]
    end
    @report.reporter = current_user.current_profile
  end

  def create
    @report = Report.new(report_params)
    @scenario = Scenario.find(report_params[:scenario_id])
    @report.confirmer = Profile.where(name: report_params[:confirmers_name]).first

    @report = @report.handle_possible_confirmation

    unless @report.was_just_confirmation?
      if @report.save
        redirect_to reports_path, notice: 'Report was successfully created.'
      else
        render :new
      end
    else
      @report.reload
      ReportsToCalculateFinder.new(@report).tag_to_calculate
      ReportsCalculating.new(@scenario.ranking).calculate
      LeaderboardUpdater.update
      redirect_to reports_path, notice: 'Report was successfully confirmed.'
    end

  end

  private



  def report_params
    params.require(:report).permit(:scenario_id, :reporter_id, :confirmers_name, :reporters_faction_id, :confirmers_faction_id, :result_id)
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
  
end

app/views/reports/_form.html.erb
<%= form_for([@scenario, @report]) do |f| %>

  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
        <% @report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">

    <%= f.label :scenario %><br />
    <% if @report.scenario %>
      <%= f.collection_select(:scenario_id, @report.scenario.ranking.scenarios, :id, :full_name, include_blank: true) %>
    <% end %>

  </div>

  <div class="form-group">
    <%= f.label :reporter, 'Me' %><br />
    <%= f.collection_select(:reporter_id, Profile.where(user_id: current_user.id), :id, :name) %>
  </div>

  <div class="form-group">
    <%= f.label :reporters_faction, 'My faction' %><br />
    <%= f.collection_select(:reporters_faction_id, @report.scenario.factions, :id, :full_name, include_blank: true) %>
  </div>

  <div class="form-group">
    <%= f.label :confirmers_name, 'My opponent' %><br />
    <%= f.text_field :confirmers_name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :confirmers_faction, "My opponent's faction" %><br />
    <%= f.collection_select(:confirmers_faction_id, @report.scenario.factions, :id, :full_name, include_blank: true) %>
  </div>

  <div class="form-group">
    <%= f.label :result %><br />
    <% if @report.scenario.ranking.game %>
      <%= f.collection_select(:result_id, @report.scenario.ranking.game.possible_results, :id, :description, include_blank: true) %>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit(class: "btn btn-primary") %>
  </div>

<% end %>

app/views/reports/index.html.erb
<h1><%= @header %></h1>

<table class="table">
  <thead>
    <tr>
      <th>Report id</th>
      <th>Game</th>
      <th>Ranking</th>
      <th>Scenario</th>
      <th>Reporter</th>
      <th>Confirmer</th>
      <th>Winner</th>
      <th>Status</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.id %></td>
        <td><%= report.scenario.ranking.game.full_name %></td>
        <td><%= report.scenario.ranking.name %></td>
        <td><%= report.scenario.full_name %></td>
        <td><%= report.reporter.name %> (<%= report.reporters_faction.full_name %>)</td>
        <td><%= report.confirmer.name %> (<%= report.confirmers_faction.full_name %>)</td>
        <td>
          <% if report.result.score_factor < 50 %>
            <%= report.confirmer.name %> (<%= report.confirmers_faction.full_name %>)
          <% elsif report.result.score_factor > 50 %>
            <%= report.reporter.name %> (<%= report.reporters_faction.full_name %>)
          <% else %>
            draw
          <% end %>
        </td>
        <td>
          <%= report.status %>
        </td>
        <td>
          <%= link_to 'Confirm', confirm_report_path(id: report, user_id: current_user), method: :patch, class: "btn" %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/reports/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1>New Report</h1>
  </div>


  <div class="panel-body">
    <%= render 'form' %>
  </div>



  <div class="panel-footer">
    <%= link_to 'Back', profiles_path %>
  </div>
</div>

app/views/reports/no_profile_error.html.erb
<h1><%= @header %></h1>

<p class="bg-warning"> Sorry, profile with that ID doesn't exists.</p>

<%= link_to 'New Profile', new_profile_path %>